// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxXxYb62yNdEzghlRs85Q5JoZj5dvk2Gc',
    appId: '1:89477570848:web:de122e81ffe8eee6067745',
    messagingSenderId: '89477570848',
    projectId: 'flymedia-app-7a2b9',
    authDomain: 'flymedia-app-7a2b9.firebaseapp.com',
    databaseURL: 'https://flymedia-app-7a2b9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flymedia-app-7a2b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfwbDKwzd1XyD6wr__SRHrG346GYq9Y3M',
    appId: '1:89477570848:android:ab9b2fb43f39ce91067745',
    messagingSenderId: '89477570848',
    projectId: 'flymedia-app-7a2b9',
    databaseURL: 'https://flymedia-app-7a2b9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flymedia-app-7a2b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAab6xIoRhgIx7InB9l7dD-iv9mfp--rlM',
    appId: '1:89477570848:ios:d160c20a6fa58fbb067745',
    messagingSenderId: '89477570848',
    projectId: 'flymedia-app-7a2b9',
    databaseURL: 'https://flymedia-app-7a2b9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flymedia-app-7a2b9.appspot.com',
    androidClientId: '89477570848-7a4p75d6tade0an7egardi9bavomlnl9.apps.googleusercontent.com',
    iosClientId: '89477570848-rm04585n10hq3aq2mrceutnghgdrtno2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flymedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAab6xIoRhgIx7InB9l7dD-iv9mfp--rlM',
    appId: '1:89477570848:ios:1ae4a9076ba300e6067745',
    messagingSenderId: '89477570848',
    projectId: 'flymedia-app-7a2b9',
    databaseURL: 'https://flymedia-app-7a2b9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flymedia-app-7a2b9.appspot.com',
    androidClientId: '89477570848-7a4p75d6tade0an7egardi9bavomlnl9.apps.googleusercontent.com',
    iosClientId: '89477570848-mmeibbvie02d7b01n4r80fgssc7aqqhs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flymedia.RunnerTests',
  );
}
